SELECT   
  SPEC_CAL.CAL_DATE,
  SUM(( SPEC_L.IN_PO_QTY )),
  SUM(( SPEC_L.REQ_QTY )),
  SPEC_ITEM.ITEM_NUM,
  SPEC_L.SPEC_NUM,
  SPEC_OTHER.SHIP_FLAG_NAME,
  SPEC_OTHER.SHIP_FLAG,
  SPEC_L_DIV_WHSE.DIV_CODE,
  SPEC_ITEM.ITEM_NAME,
  SPEC_PL.C_BNAL,
  SPEC_VEND.VEND_NAME,
  SPEC_VEND.VENDOR_NUM,
  SPEC_VEND.PARENT_NUM,
  PERF_CAL.CAL_DATE,
  SPEC_SHIP_VEND.VENDOR_NUM,
  SPEC_SHIP_VEND.VEND_NAME,
  spec_MIV.VENDOR_NAME,
  spec_MIV.VENDOR_NUM,
  spec_MIV.STOCK_CONTROL,
  spec_MIV.LEAD_TIME,
  DECODE(NVL(spec_MVW.vend_whse_status,'D'),'D',spec_MIV.PROD_MANAGER_NAME,spec_MVW.PROD_MANAGER_NAME),
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'), 'D',spec_MIV.PROD_MANAGER_NAME, spec_MVW.PROD_MANAGER_NAME),
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'),'D',spec_MIV.VEND_PARENT_NAME, spec_MVW.VEND_PARENT_NAME),
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'),'D',spec_MIV.VEND_PARENT_NUM, spec_MVW.VEND_PARENT_NUM),
  
  -- SPEC_L.LINE_NUM,
	SPEC_L.SPEC_ID,			 
  
  SPEC_OTHER.ship_flag_l,
  
  -- SPEC_L.user_chg_flag,
  SPEC_L.SPEC_L_ID,
  
  SPEC_L.DIV_CODE,
  SPEC_L.ORDER_NUM,
  SPEC_L.SAP_ORDTEXT
FROM
  KDW.DWD_CALENDAR  SPEC_CAL,
  KDW.DWF_SPEC_L  SPEC_L,
  KDW.DWD_ITEM  SPEC_ITEM,
  KDW.DWD_SPEC_OTHER  SPEC_OTHER,
  KDW.DWD_DIVISION  SPEC_L_DIV_WHSE,
  KDW.DWD_PRICE_LIST  SPEC_PL,
  KDW.DWD_VENDOR  SPEC_VEND,
  KDW.DWD_CALENDAR  PERF_CAL,
  KDW.DWD_VENDOR  SPEC_SHIP_VEND,
  KDW.DWE_MAIN_ITEM_V  spec_MIV,
  KDW.DWE_MAIN_VEND_WHSE  spec_MVW,
  KDW.DWD_SPEC_PO  SPEC_PO
WHERE
  ( SPEC_CAL.ID_DATE=SPEC_L.ID_SPEC_DATE  )
  AND  ( SPEC_ITEM.ID_ITEM=SPEC_L.ID_ITEM  )
  AND  ( SPEC_PL.ID_PRICE_LIST=SPEC_L.ID_PRICE_LIST  )
  AND  ( SPEC_L.ID_VENDOR=SPEC_VEND.ID_VENDOR  )
  AND  ( SPEC_L.ID_SPEC_PO=SPEC_PO.ID_SPEC_PO  )
  AND  ( SPEC_L.ID_SPEC_OTHER=SPEC_OTHER.ID_SPEC_OTHER  )
  AND  ( SPEC_PO.ID_PERFORM_DATE=PERF_CAL.ID_DATE  )
  AND  ( SPEC_L.ID_SPEC_OTHER IN(SELECT id_spec_other FROM kdw.dwd_spec_other WHERE is_spec_line = 'Y')  )
  AND  ( SPEC_L_DIV_WHSE.ID_DIV=SPEC_L.ID_DIV_WHSE  )
  AND  ( SPEC_SHIP_VEND.ID_VENDOR=SPEC_L.ID_SHIP_VENDOR  )
  AND  ( spec_MIV.ITEM_NUM=SPEC_L.ITEM_NUM  )
  AND  ( spec_MVW.ITEM_NUM(+)=SPEC_L.ITEM_NUM and spec_MVW.ID_WHSE(+)=SPEC_L.ID_WHSE  )
  AND  (
  SPEC_CAL.CAL_DATE  >=  @variable('Ñ êàêîé äàòû ó÷èòûâàòü çàêàçû')
  )
GROUP BY
  SPEC_CAL.CAL_DATE, 
  SPEC_ITEM.ITEM_NUM, 
  SPEC_L.SPEC_NUM, 
  SPEC_OTHER.SHIP_FLAG_NAME, 
  SPEC_OTHER.SHIP_FLAG, 
  SPEC_L_DIV_WHSE.DIV_CODE, 
  SPEC_ITEM.ITEM_NAME, 
  SPEC_PL.C_BNAL, 
  SPEC_VEND.VEND_NAME, 
  SPEC_VEND.VENDOR_NUM, 
  SPEC_VEND.PARENT_NUM, 
  PERF_CAL.CAL_DATE, 
  SPEC_SHIP_VEND.VENDOR_NUM, 
  SPEC_SHIP_VEND.VEND_NAME, 
  spec_MIV.VENDOR_NAME, 
  spec_MIV.VENDOR_NUM, 
  spec_MIV.STOCK_CONTROL, 
  spec_MIV.LEAD_TIME, 
  DECODE(NVL(spec_MVW.vend_whse_status,'D'),'D',spec_MIV.PROD_MANAGER_NAME,spec_MVW.PROD_MANAGER_NAME), 
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'), 'D',spec_MIV.PROD_MANAGER_NAME, spec_MVW.PROD_MANAGER_NAME), 
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'),'D',spec_MIV.VEND_PARENT_NAME, spec_MVW.VEND_PARENT_NAME), 
  DECODE(NVL(spec_MVW.vend_whse_status, 'D'),'D',spec_MIV.VEND_PARENT_NUM, spec_MVW.VEND_PARENT_NUM), 
  
 -- SPEC_L.LINE_NUM, 
	SPEC_L.SPEC_ID,			 
  
  SPEC_OTHER.ship_flag_l, 
  
  -- SPEC_L.user_chg_flag, 
   SPEC_L.SPEC_L_ID,
   
  SPEC_L.DIV_CODE, 
  SPEC_L.ORDER_NUM, 
  SPEC_L.SAP_ORDTEXT
HAVING
  ( 
  SUM(( SPEC_L.IN_PO_QTY ))  !=  SUM(SPEC_L.REQ_QTY)
  )